### ISSUE TITLE
drop cargo-xbuild build dependency

### ISSUE THREAD

**Issue by japaric** [iqlusioninc/usbarmory.rs#4]
`cargo-xbuild` requires nightly and it's only reason building the examples requires nightly.

This tool is required because, currently, there's no *bare metal* Cortex-A support in rustc / rustup. (See `rustc --print target-list` & `rustup target list`). If we add support for this target to rustc / rustup ([reference PR](https://github.com/rust-lang/rust/pull/53822)) then we'll be able to build all the code in this repo using a stable toolchain.

Hopefully, we should be able get that target support in by the 1.42 beta cutoff so all code will compile on the stable 1.42 release.

**Comment by tarcieri** [comment]
That'd be great. In the meantime I think we're fine with nightly, but supporting stable would be quite nice.

**Comment by japaric** [comment]
> If we add support for this target to rustc / rustup

Submitted a PR: rust-lang/rust#68253
